server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/proma?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: jdb4497@gmail.com
    password: wkdekqls02!@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    hibernate:
      ddl-auto: update

  properties:
    hibernate:
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
